config/routes.rb
Rails.application.routes.draw do
  root to: 'users#profile'

  get 'signup' => 'users#new'
  resources :users, only: [:new, :create, :show]  do
    resources :wishes
    post 'add_friend', on: :member
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :wishes
  validates :email, presence: true
  has_many :friendships
  has_many :friends, through: :friendships
end

app/models/wish.rb
class Wish < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to login_path unless current_user
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user
  skip_before_action :verify_authenticity_token

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = current_user
    render :show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to signup_path
    end
  end

  def add_friend
    @user = User.find(params[:id])

    unless @user == current_user
      head :unauthorized
      return
    end

    @friend = User.find(params[:friend_id])

    @user.friends << @friend
    @friend.friends << @user

    redirect_to @user, notice: 'Friend added successfully.'
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :require_user
  before_action :set_user
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  def index
    @wishes = @user.wishes
  end

  def show
  end

  def new
    @wish = @user.wishes.build
  end

  def create
    @wish = @user.wishes.build(wish_params)

    if @wish.save
      redirect_to user_wish_path(@user, @wish)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @wish.update(wish_params)
      redirect_to user_wish_path(@user, @wish)
    else
      render :edit
    end
  end

  def destroy
    @wish.destroy
    redirect_to user_wishes_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_wish
    @wish = @user.wishes.find(params[:id])
  end

  def wish_params
    params.require(:wish).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wishlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <%= link_to(root_path) do %>
          <h1>Home</h1>
        <% end %>

        <div class="nav">
          
          <% if current_user %>
            <ul>
              <li><%= current_user.email %></li>
              <li><%= button_to "Log out", logout_path, method: "delete", class: 'btn btn-small' %></li>
            </ul>
          <% else %>
            <ul>
              <li><%= link_to "Login", 'login' %></li>
              <li><%= link_to "Signup", 'signup' %></li>
            </ul>
          <% end %>
          
        </div>
      </div>
    </div>


    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<div class="signup">
  <div class="container">
    
    <%= form_for(@user) do |f| %>
      <div class="field"> 
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
      </div> 
      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
      </div> 
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div> 
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div> 
      <div class="actions"> 
        <%= f.submit "Sign Up", class: "btn-submit" %>
      </div>
    <% end %> 

  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %>'s Profile</h1>


<%= link_to "Your Wishes", user_wishes_path(current_user) %>

<h2>Friends</h2>

<ul>
  <% @user.friends.each do |friend| %>
    <li>
      <%= link_to friend.first_name, user_path(friend) %>
    </li>
  <% end %>
</ul>

<% if @user == current_user %>
  <h2>Add a Friend</h2>

  <%= form_with url: add_friend_user_path(@user), method: :post do %>
    <div class="field">
      <%= label_tag :friend_id, "Friend's ID" %>
      <%= text_field_tag :friend_id %>
    </div>

    <div class="actions">
      <%= submit_tag "Add Friend" %>
    </div>
  <% end %>
<% end %>

app/views/wishes/_form.html.erb
<%= form_with(model: [@user, @wish], local: true) do |form| %>
  <% if wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
        <% wish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Edit Wish</h1>

<%= render "form", wish: @wish %>

app/views/wishes/index.html.erb
<h1><%= @user.first_name %>'s Wishes</h1>

<ul>
  <% @wishes.each do |wish| %>
    <li>
      <%= link_to wish.title, user_wish_path(@user, wish) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Wish", new_user_wish_path(@user) %>

app/views/wishes/new.html.erb
<h1>New Wish</h1>

<%= form_with model: @wish do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @wish.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wishes/show.html.erb
<h5><li><%= link_to "Home", root_path %></li></h5>

<h1><%= @wish.title %></h1>

<p><%= @wish.body %></p>

<ul>
  <li><%= link_to "Edit", edit_user_wish_path(@user, @wish) %></li>
  <li><%= link_to "Delete", user_wish_path(@user, @wish), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Delete this wish?"
                  } %></li>
</ul>